### ISSUE TITLE
com.bin.david.form.core.SmartTable$1.run(SmartTable.java:198)

### ISSUE THREAD

**Issue by lipei2015** [huangyanbin/smartTable#130]
大家有没有遇到不定时闪退的问题？
报错内容：com.bin.david.form.core.SmartTable$1.run(SmartTable.java:198)

**Comment by JakeWoki** [comment]
你是不是改了代码？198行不是run啊

**Comment by lipei2015** [comment]
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.bin.david.form.component.XSequence.setHeight(int)' on a null object reference
	at com.bin.david.form.core.SmartTable$1.run(SmartTable.java:198)
	at java.lang.Thread.run(Thread.java:818)

**Comment by lipei2015** [comment]
这是报错日志，我没有改代码

**Comment by JakeWoki** [comment]
是不是表格更新时退出界面造成的？

**Comment by lipei2015** [comment]
是表格更新时，但是没有退出界面

**Comment by skymxc** [comment]
这个问题解决了吗?我也遇到了这个问题

版本是 1.7.1

```   
 java.lang.NullPointerException: Attempt to invoke virtual method 'void com.bin.david.form.component.XSequence.setHeight(int)' on a null object reference
        at com.bin.david.form.core.SmartTable$1.run(SmartTable.java:198)
        at java.lang.Thread.run(Thread.java:784)
```

**Comment by skymxc** [comment]
出问题的场景是在 Fragment切换时出现的.
显示在Fragment里是没有问题的.刷新完成后切换到另一个 Fragment 就崩了

有多个 fragment 在 viewPager 里

**Comment by 978749951** [comment]
经常退出了表格页面还报闪退的错误，有没有什么解决办法？

**Comment by skymxc** [comment]
我这边定位到的错误是因为 在SmartTable 的 onDetachedFromWindow() 里进行了资源的释放,而对应的在 onAttachedToWindow() 没有初始化代码; 初始化代码只有在 构造方法被调用了. 但view再次被附加到 window的时候就会崩溃了,因为还没有初始化. 另外,如果 在 SmartTable 释放资源后调用 setData() 或者 notifyDataChanged() 都会异常.

**Comment by 978749951** [comment]
“ 在 SmartTable 释放资源后调用 setData() "是什么意思呢？

**Comment by skymxc** [comment]
@978749951 就是在release() 被调用后 setData()

**Comment by tracy0523** [comment]
老哥，这个问题现在解决了没。
