### ISSUE TITLE
关于父级Layout.removeAllViews()导致的崩溃

### ISSUE THREAD

**Issue by Krosxx** [huangyanbin/smartTable#172]
错误信息: 
 ```
java.lang.ClassCastException: xxx.xxx.Application cannot be cast to android.app.Activity
        at com.bin.david.form.core.SmartTable.onDetachedFromWindow(SmartTable.java:591)
        at android.view.View.dispatchDetachedFromWindow(View.java:18566)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3785)
        at android.view.ViewGroup.removeAllViewsInLayout(ViewGroup.java:5587)
```

报错代码: 
```
 protected void onDetachedFromWindow() {
        super.onDetachedFromWindow();
        if (tableData != null && getContext() != null) {
            if (((Activity) getContext()).isFinishing()) {
                release();
            }
        }
    }
```

**Comment by saber900517** [comment]
Application的Context没有isFinishing()这个方法，你应该传入Activity的Context。Application和Activity虽然都是Context的子类，但是两者实现还是不一样的。

**Comment by Krosxx** [comment]
> Application的Context没有isFinishing()这个方法，你应该传入Activity的Context。Application和Activity虽然都是Context的子类，但是两者实现还是不一样的。

可是使用View的场景 并不一定是在Activity中（极端时比如悬浮窗）， 还是判断下(getContext() instanceOf Activity) 比较好😁

**Comment by saber900517** [comment]
那种时候用的就不是AlertDialog这种东西了，用的是DialogActivity，启动模式是newTask

**Comment by Krosxx** [comment]
其实这是在Fragment里报的错
