### ISSUE TITLE
添加smartTable控件但是未使用的情况下会报空指针

### ISSUE THREAD

**Issue by SuperOverlow** [huangyanbin/smartTable#20]
请问这是什么问题呢

**Comment by SuperOverlow** [comment]
为啥我的还是停止运行

**Comment by huangyanbin** [comment]
你贴下错误代码

**Comment by SuperOverlow** [comment]
public class MainActivity extends AppCompatActivity {
    private SmartTable<UserInfo> table;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        table = (SmartTable<UserInfo>) findViewById(R.id.table);
        List<UserInfo> list = new ArrayList<>();
        table.getConfig().setShowTableTitle(false);
        table.getConfig().setFixedYSequence(true);
        table.getConfig().setFixedCountRow(false);
        table.getConfig().setShowXSequence(false);
        table.getConfig().setShowYSequence(false);
        table.setZoom(true,2,0.2f);
    }
}
没添加数据 什么都没 就是测试一下就报异常

**Comment by huangyanbin** [comment]
贴下Log报错信息

**Comment by SuperOverlow** [comment]
java.lang.NullPointerException
                                                                            at com.bin.david.form.core.SmartTable.onDetachedFromWindow(SmartTable.java:430)
                                                                            at android.view.View.dispatchDetachedFromWindow(View.java:12648)
                                                                            at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2590)
                                                                            at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2590)
                                                                            at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2590)
                                                                            at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2590)
                                                                            at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2590)
                                                                            at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2590)
                                                                            at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:2849)
                                                                            at android.view.ViewRootImpl.doDie(ViewRootImpl.java:5309)
                                                                            at android.view.ViewRootImpl.die(ViewRootImpl.java:5286)
                                                                            at android.view.WindowManagerGlobal.removeViewLocked(WindowManagerGlobal.java:346)
                                                                            at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:301)
                                                                            at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:84)
                                                                            at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3534)
                                                                            at android.app.ActivityThread.access$1400(ActivityThread.java:138)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1253)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:136)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5131)
                                                                            at java.lang.reflect.Method.invokeNative(Native Method)
                                                                            at java.lang.reflect.Method.invoke(Method.java:515)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
                                                                            at dalvik.system.NativeStart.main(Native Method)

**Comment by huangyanbin** [comment]
我贴了你代码运行，没有报任何错误，你更新了版本吗？1.8.3版本

**Comment by SuperOverlow** [comment]
更新了 运行的时候是不会报错的  一按返回就报错

**Comment by huangyanbin** [comment]
贴错误信息哈，我这边啥错都没报

**Comment by SuperOverlow** [comment]
就上面那么多信息了 我又试了一次 表里有数据之后返回没问题 没数据还是一样的错误

**Comment by huangyanbin** [comment]
onDetachedFromWindow 这个方法在很早之前就去掉了，现在1.8.3里面都没有这个方法

**Comment by huangyanbin** [comment]
你再看下Log.你真的贴错了，你贴的错误是很早的版本的
