### ISSUE TITLE
setdata 太长就会报错吗

### ISSUE THREAD

**Issue by HuRuWo** [huangyanbin/smartTable#24]

**Comment by HuRuWo** [comment]
使用的版本  compile 'com.github.huangyanbin:SmartTable:1.8.7'

**Comment by HuRuWo** [comment]
测试 大概setdata 60~70以上就会报错 
```
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Rect.height()' on a null object reference
                                                                     at com.bin.david.form.core.SmartTable.requestReMeasure(SmartTable.java:268)
                                                                     at com.bin.david.form.core.SmartTable.onMeasure(SmartTable.java:286)
                                                                     at android.view.View.measure(View.java:18017)
                                                                     at android.support.constraint.ConstraintLayout.internalMeasureChildren(ConstraintLayout.java:934)
                                                                     at android.support.constraint.ConstraintLayout.onMeasure(ConstraintLayout.java:973)
                                                                     at android.view.View.measure(View.java:18017)
                                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5698)
                                                                     at android.widget.FrameLayout.onMeasure(FrameLayout.java:465)
                                                                     at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                                                                     at android.view.View.measure(View.java:18017)
                                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5698)
                                                                     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1692)
                                                                     at android.widget.LinearLayout.measureVertical(LinearLayout.java:760)
                                                                     at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
                                                                     at android.view.View.measure(View.java:18017)
                                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5698)
                                                                     at android.widget.FrameLayout.onMeasure(FrameLayout.java:465)
                                                                     at android.view.View.measure(View.java:18017)
                                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5698)
                                                                     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1692)
                                                                     at android.widget.LinearLayout.measureVertical(LinearLayout.java:760)
                                                                     at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
                                                                     at android.view.View.measure(View.java:18017)
                                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5698)
                                                                     at android.widget.FrameLayout.onMeasure(FrameLayout.java:465)
                                                                     at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2778)
                                                                     at android.view.View.measure(View.java:18017)
                                                                     at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2451)
                                                                     at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1433)
                                                                     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1668)
                                                                     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1311)
                                                                     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6667)
                                                                     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:802)
                                                                     at android.view.Choreographer.doCallbacks(Choreographer.java:605)
                                                                     at android.view.Choreographer.doFrame(Choreographer.java:574)
                                                                     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:788)
                                                                     at android.os.Handler.handleCallback(Handler.java:815)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                     at android.os.Looper.loop(Looper.java:194)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5877)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
```

**Comment by HuRuWo** [comment]
我找到了 闪退的原因了
就是使用了
ConstraintLayout 布局作为父布局，同时setdata 数据太长 
希望修复该bug

**Comment by kona5362** [comment]
![image](https://user-images.githubusercontent.com/28619342/36527905-492a6492-17ee-11e8-89eb-be10bdcf4c50.png)
遇到类似的错误了。

1.7.1版本上没事
1.8.7版本上就会出现这个问题
和题主不一样
我不是ConstraintLayout 布局作为父布局

刚过完年回来，祝作者新年快乐，哈哈

**Comment by kona5362** [comment]
![image](https://user-images.githubusercontent.com/28619342/36527905-492a6492-17ee-11e8-89eb-be10bdcf4c50.png)
遇到类似的错误了。

1.7.1版本上没事
1.8.7版本上就会出现这个问题
和题主不一样
我不是ConstraintLayout 布局作为父布局

刚过完年回来，祝作者新年快乐，哈哈

**Comment by huangyanbin** [comment]
已修复 1.8.8
