### ISSUE TITLE
table没有设置listener，用手指快速点击table有几率发生以下错误，应该是多点触控没有捕获异常吧，

### ISSUE THREAD

**Issue by 957919019** [huangyanbin/smartTable#32]
控件初始化：
`

 private void initWidget()
    {
        ICellBackgroundFormat<CellInfo> backgroundFormat = new BaseCellBackgroundFormat<CellInfo>()
        {
            @Override
            public int getBackGroundColor(CellInfo cellInfo)
            {
                if (cellInfo.row % 2 == 0)
                {
                    return ContextCompat.getColor(mActivity, R.color.windows_bg);
                }
                return TableConfig.INVALID_COLOR;
            }
        };
        tb_table.setZoom(false, 3, 0.2f); // 大小
        tb_table.getConfig().setShowColumnTitle(true)
                .setShowXSequence(false).setShowYSequence(false)
                .setColumnTitleBackground(new BaseBackgroundFormat(getResources().getColor(R.color.windows_bg)))
                .setCountBackground(new BaseBackgroundFormat(getResources().getColor(R.color.colorAccent))) // 总计背景
                .setCountBgCellFormat(new ICellBackgroundFormat<Column>() // 总结字体颜色
                {
                    @Override
                    public void drawBackground(Canvas canvas, Rect rect, Column column, Paint paint)
                    {
                    }

                    @Override
                    public int getTextColor(Column column)
                    {
                        return ContextCompat.getColor(mActivity, R.color.white);
                    }
                })
                .setFixedCountRow(true) // 固定统计行
                .setFixedXSequence(true) // 固定顶部
                .setFixedTitle(true) // 固定列标题
                .setContentCellBackgroundFormat(backgroundFormat) // 背景
                .setShowTableTitle(true) // 表名
                .setTableTitleStyle(new FontStyle(mActivity, 20, getResources().getColor(R.color.colorPrimary)).setAlign(Paint.Align.CENTER));
    }
`

快速点击后报错：
java.lang.IllegalArgumentException: pointerIndex out of range
                                                     at android.view.MotionEvent.nativeGetAxisValue(Native Method)
                                                     at android.view.MotionEvent.getX(MotionEvent.java:2381)
                                                     at android.support.v4.view.ViewPager.onInterceptTouchEvent(ViewPager.java:2092)
                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2402)
                                                     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
                                                     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
                                                     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
                                                     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
                                                     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
                                                     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
                                                     at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:559)
                                                     at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1870)
                                                     at android.app.Activity.dispatchTouchEvent(Activity.java:3236)
                                                     at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
                                                     at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
                                                     at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:521)
                                                     at android.view.View.dispatchPointerEvent(View.java:10952)
                                                     at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5121)
                                                     at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4973)
                                                     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4504)
                                                     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4557)
                                                     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4523)
                                                     at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4656)
                                                     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4531)
                                                     at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4713)
                                                     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4504)
                                                     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4557)
                                                     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4523)
                                                     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4531)
                                                     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4504)
                                                     at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7011)
                                                     at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6940)
                                                     at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6901)
                                                     at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7121)
                                                     at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                     at android.os.MessageQueue.nativePollOnce(Native Method)
                                                     at android.os.MessageQueue.next(MessageQueue.java:323)
                                                     at android.os.Looper.loop(Looper.java:136)
                                                     at android.app.ActivityThread.main(ActivityThread.java:6682)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

**Comment by 957919019** [comment]
找到问题所在了，原因是我的viewpager的滑动与table可能存在冲突，这个问题在我禁用了Viewpager手势后恢复正常

**Comment by gongsiyi123** [comment]
请问那是不是就不能使用ViewPager的滑动手势了？

**Comment by kscMaster** [comment]
在我项目里，为了尽快解决冲突，最快的方式就是禁用滑动手势
