### ISSUE TITLE
setContentStyle会报空指针异常

### ISSUE THREAD

**Issue by muhaha31** [huangyanbin/smartTable#41]
代码如下：
`        mTermSmartTable.getConfig()
                .setColumnTitleStyle(new FontStyle(21, Color.BLACK))
                .setContentStyle(new FontStyle(this, 18, Color.BLACK))
                .setShowTableTitle(false)
                .setShowXSequence(false)
                .setShowYSequence(false)
                .setTextLeftOffset(5);`

> 

FATAL EXCEPTION: Thread-603
                                                                     java.lang.NullPointerException
                                                                         at com.bin.david.form.utils.DrawUtils.getTextHeight(DrawUtils.java:22)
                                                                         at com.bin.david.form.core.TableMeasurer.getTableHeight(TableMeasurer.java:120)
                                                                         at com.bin.david.form.core.TableMeasurer.measure(TableMeasurer.java:30)
                                                                         at com.bin.david.form.core.SmartTable$1.run(SmartTable.java:233)
                                                                         at java.lang.Thread.run(Thread.java:841)

**Comment by huangyanbin** [comment]
已修复

**Comment by aiynmm** [comment]
现在怎么又出现这个空指针错误了啊！请问是已经修复了吗？
