### ISSUE TITLE
更新数据，并发异常 ConcurrentModificationException

### ISSUE THREAD

**Issue by littleloulou** [huangyanbin/smartTable#89]
java.util.ConcurrentModificationException
                                                    at java.util.ArrayList$Itr.next(ArrayList.java:860)
                                                    at com.bin.david.form.core.TableParser.addArrayNode(TableParser.java:75)
                                                    at com.bin.david.form.core.TableParser.parse(TableParser.java:40)
                                                    at com.bin.david.form.core.SmartTable$1.run(SmartTable.java:232)
                                                    at java.lang.Thread.run(Thread.java:764)

**Comment by zhangchaoxu** [comment]
我也遇到了类似问题，我尝试将foreach改成for，但是又出现了新的数组越界问题。
后来发现是因为是两个notifyDataChanged调用时间太近了，把时间拉长可以解决问题。
但是这并不是想要的结果，所以还希望作者能解决，谢谢
@huangyanbin
