### ISSUE TITLE
更新数据，抛出了并发修改异常

### ISSUE THREAD

**Issue by littleloulou** [huangyanbin/smartTable#90]
java.util.ConcurrentModificationException
                                                    at java.util.ArrayList$Itr.next(ArrayList.java:860)
                                                    at com.bin.david.form.core.TableParser.addArrayNode(TableParser.java:75)
                                                    at com.bin.david.form.core.TableParser.parse(TableParser.java:40)
                                                    at com.bin.david.form.core.SmartTable$1.run(SmartTable.java:232)
                                                    at java.lang.Thread.run(Thread.java:764)

**Comment by yyy000112** [comment]
你看看是不是重复或者连续不断地更新数据了

**Comment by littleloulou** [comment]
> 你看看是不是重复或者连续不断地更新数据了

嗯，代码确实有两次比较近的数据更新操作，作者封装的API已经更新了数据，我又调用了一次原生的

**Comment by HiWilliam** [comment]
你好，我也在学习使用，请问smarttable如何实现页面的更新（页面所有数据都替换掉）。 @littleloulou

**Comment by ChaoquanTao** [comment]
> 你好，我也在学习使用，请问smarttable如何实现页面的更新（页面所有数据都替换掉）。 @littleloulou

我遇到了一样的问题，请问有什么解决办法么，我是用setTableData来刷新数据的

**Comment by HiWilliam** [comment]
> > 你好，我也在学习使用，请问smarttable如何实现页面的更新（页面所有数据都替换掉）。 @littleloulou
> 
> 我遇到了一样的问题，请问有什么解决办法么，我是用setTableData来刷新数据的

什么问题？是数据无法显示吗？我是先清空list，在给list赋值。用setTableData添加上去的。

**Comment by HiWilliam** [comment]
> > 你好，我也在学习使用，请问smarttable如何实现页面的更新（页面所有数据都替换掉）。 @littleloulou
> 
> 我遇到了一样的问题，请问有什么解决办法么，我是用setTableData来刷新数据的
https://github.com/huangyanbin/smartTable/issues/133

**Comment by ChaoquanTao** [comment]
> > > 你好，我也在学习使用，请问smarttable如何实现页面的更新（页面所有数据都替换掉）。 @littleloulou
> > 
> > 
> > 我遇到了一样的问题，请问有什么解决办法么，我是用setTableData来刷新数据的
> 
> 什么问题？是数据无法显示吗？我是先清空list，在给list赋值。用setTableData添加上去的。

我是用handler在主线程接收list, 然后用tableData.set()更新tableData,然后用table.setTableData()更新table,但是数据几百毫秒刷新一次时就会出现并发修改异常，我是不是应该先清空tableData

**Comment by littleloulou** [comment]
目前是通过这种方式，来避免这个问题的，效果还行，仅更新数据部分代码
    private long mLastNotifyDataChangeTime = 0;
    private TableData<DeviceInfo> mTableData;
    private SmartTable<DeviceInfo> mTable;

    private void notifyDataChange() {
        if (System.currentTimeMillis() - mLastNotifyDataChangeTime < 1000) {
            return;
        }
        mTableData.setT(mCurrentPageDevice);
        mTable.notifyDataChanged();
        mLastNotifyDataChangeTime = System.currentTimeMillis();
    } @ChaoquanTao @wuhaodiyi
