### ISSUE TITLE
Activity销毁时候报错，log如下

### ISSUE THREAD

**Issue by lyy19900130** [huangyanbin/smartTable#98]
08-29 19:17:36.302 28278 28278 E AndroidRuntime: java.lang.ClassCastException: android.view.ContextThemeWrapper cannot be cast to android.app.Activity
08-29 19:17:36.302 28278 28278 E AndroidRuntime:        at com.bin.david.form.core.SmartTable.onDetachedFromWindow(SmartTable.java:591)
08-29 19:17:36.302 28278 28278 E AndroidRuntime:        at android.view.View.dispatchDetachedFromWindow(View.java:18427)
08-29 19:17:36.302 28278 28278 E AndroidRuntime:        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3771)

**Comment by lyy19900130** [comment]
自己解决了

**Comment by zhangjie201412** [comment]
帅哥，有遇到过编译报错吗，我使用AS 3.1版本
Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

Failed to resolve: com.github.huangyanbin:SmartTable:2.2.0
Show in File
Show in Project Structure dialog
